const s = (o, e, t) => {
  const r = new Error(o);
  r.name = "FetcherError", r.url = e.url, r.status = e.status, r.statusText = e.statusText, r.responseText = t;
  try {
    const n = JSON.parse(t);
    r.responseJson = n;
  } catch {
  }
  return r;
}, c = async (o, e) => {
  const t = await fetch(o, e), r = await t.text();
  if (!t.ok)
    throw s("An error occurred while fetching", t, r);
  try {
    return JSON.parse(r);
  } catch {
    throw s("An error occurred while parsing", t, r);
  }
}, a = async (o, e) => {
  const t = await fetch(o, {
    method: "POST",
    ...e
  }), r = await t.text();
  if (!t.ok)
    throw s("An error occurred while fetching", t, r);
  try {
    return JSON.parse(r);
  } catch {
    throw s("An error occurred while parsing", t, r);
  }
};
export {
  c as fetchData,
  s as fetcherError,
  a as postData
};
